# foundry.toml
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.18"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# Make sure there's no extra whitespace in your .env file
# .env
[etherscen]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# source .env
# echo "RPC URL: $https://eth-sepolia.g.alchemy.com/v2/5ODMxw_yWtBNgoySZMLb8APkoIFCtNfW"
# echo "Private Key is set: $(if [ -n "$PRIVATE_KEY" ]; then echo "yes"; else echo "no"; fi)"# To verify the configuration is loaded correctly, create a simple test script:
# # test_config.sh
# #!/bin/bash
